[package]
name = "markdown-editor"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
futures.workspace = true
gpui.workspace = true
gpui-component = { workspace = true, features = ["tree-sitter-markdown"] }
markdown-source.workspace = true
thiserror.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
gpui-component-assets.workspace = true
gpui_platform = { workspace = true, features = ["test-support"] }
ropey.workspace = true
rust-embed = { version = "8.7.2", features = ["include-exclude"] }

[lints]
workspace = true
