FROM alpine:3.22

RUN apk add --no-cache openssh \
    && adduser -D -s /bin/sh onetcli \
    && echo 'onetcli:onetcli-pass' | chpasswd \
    && ssh-keygen -A

COPY sshd_config /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-e"]
