[package]
name = "rocketmq-runtime"
version = "0.15.2"
publish.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
connection_tunnel.workspace = true
dashmap.workspace = true
hmac.workspace = true
middleware-runtime.workspace = true
one-core.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
rust-i18n.workspace = true
tokio = { workspace = true, features = ["io-util", "net", "rt-multi-thread", "macros", "sync", "time"] }
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
