//! Checked readers for internal metadata query results.
//!
//! Metadata queries (schema/table/column listings) are generated by the
//! application, so the expected kind of each column is known. This module reads
//! those cells from the authoritative typed batch first and only falls back to
//! the legacy projection when no typed batch is present. Ambiguous binary cells
//! are decoded strictly with a caller-provided charset; failures surface as
//! errors instead of silently rendering hex or NULL.

use crate::executor::{QueryCellRef, QueryResult};

#[derive(Debug, thiserror::Error)]
pub enum MetadataReadError {
    #[error("metadata result shape is invalid: {0}")]
    Shape(#[from] crate::executor::QueryResultError),
    #[error("metadata cell ({row_index}, {column_index}) is a decode error: {diagnostic}")]
    DecodeError {
        row_index: usize,
        column_index: usize,
        diagnostic: String,
    },
    #[error("metadata cell ({row_index}, {column_index}) could not be decoded: {reason}")]
    Undecoded {
        row_index: usize,
        column_index: usize,
        reason: String,
    },
    #[error(
        "metadata cell ({row_index}, {column_index}) bytes are invalid for charset `{charset}`"
    )]
    InvalidCharset {
        row_index: usize,
        column_index: usize,
        charset: String,
    },
}

/// Read one metadata cell expected to be text.
///
/// Decoded text-like values are returned as-is. Ambiguous binary bytes (the
/// MySQL `character_set_results=binary` case) are strictly decoded with
/// `charset`; invalid bytes fail instead of degrading to hex or NULL.
pub fn metadata_text(
    result: &QueryResult,
    row_index: usize,
    column_index: usize,
    charset: &str,
) -> Result<Option<String>, MetadataReadError> {
    if let Some(batch) = result.typed_batch() {
        let Some(cell) = batch
            .rows
            .get(row_index)
            .and_then(|row| row.cells.get(column_index))
        else {
            return Ok(None);
        };
        return typed_cell_text(cell, row_index, column_index, charset);
    }

    let view = result.typed_view()?;
    match view.cell(row_index, column_index) {
        Some(QueryCellRef::Null) | None => Ok(None),
        Some(QueryCellRef::Text(text)) => Ok(Some(text.to_string())),
        Some(QueryCellRef::Binary(bytes)) => {
            decode_bytes(bytes, row_index, column_index, charset).map(Some)
        }
    }
}

fn typed_cell_text(
    cell: &db_value::CellState,
    row_index: usize,
    column_index: usize,
    charset: &str,
) -> Result<Option<String>, MetadataReadError> {
    use db_value::{CellState, DbValue};
    match cell {
        CellState::Decoded(DbValue::Null) => Ok(None),
        CellState::Decoded(DbValue::Binary(bytes)) => {
            decode_bytes(bytes, row_index, column_index, charset).map(Some)
        }
        CellState::Decoded(value) => Ok(Some(value.to_string())),
        CellState::DecodeError { diagnostic, .. } => Err(MetadataReadError::DecodeError {
            row_index,
            column_index,
            diagnostic: diagnostic.clone(),
        }),
        CellState::Undecoded { reason, .. } => Err(MetadataReadError::Undecoded {
            row_index,
            column_index,
            reason: reason.clone(),
        }),
    }
}

fn decode_bytes(
    bytes: &[u8],
    row_index: usize,
    column_index: usize,
    charset: &str,
) -> Result<String, MetadataReadError> {
    let decoder = crate::query_result_normalization::mysql_text_decoder_for_charset(charset)
        .ok_or_else(|| MetadataReadError::InvalidCharset {
            row_index,
            column_index,
            charset: charset.to_string(),
        })?;
    if !decoder.is_valid(bytes) {
        return Err(MetadataReadError::InvalidCharset {
            row_index,
            column_index,
            charset: charset.to_string(),
        });
    }
    Ok(decoder.decode_validated(bytes.to_vec()))
}

/// Read an optional metadata integer cell.
pub fn metadata_integer(
    result: &QueryResult,
    row_index: usize,
    column_index: usize,
) -> Result<Option<i64>, MetadataReadError> {
    let text = metadata_text(result, row_index, column_index, "utf8mb4")?;
    Ok(text.and_then(|value| value.trim().parse::<i64>().ok()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::executor::{BinaryCell, QueryColumnMeta};
    use db_value::{CellState, ColumnDescriptor, DbValue, Nullability, ResultBatch, ResultRow};
    use std::sync::Arc;

    fn typed_result(cells: Vec<CellState>) -> QueryResult {
        let columns = (0..cells.len())
            .map(|index| ColumnDescriptor {
                id: format!("column:{index}"),
                label: format!("c{index}"),
                native_type: "VARCHAR".to_string(),
                logical_type: "Text".to_string(),
                nullable: Nullability::Unknown,
                charset: None,
                collation: None,
                precision: None,
                scale: None,
            })
            .collect();
        let batch =
            ResultBatch::try_new(0, columns, vec![ResultRow { id: 0, cells }], true).unwrap();
        QueryResult {
            sql: "metadata".to_string(),
            columns: vec!["c0".to_string()],
            column_meta: vec![QueryColumnMeta::new("c0", "VARCHAR")],
            rows: vec![vec![None]],
            binary_cells: vec![],
            elapsed_ms: 0,
            typed_batch: Some(Arc::new(batch)),
        }
    }

    #[test]
    fn decodes_ambiguous_binary_metadata_as_text() {
        let result = typed_result(vec![CellState::Decoded(DbValue::Binary(b"mysql".to_vec()))]);
        assert_eq!(
            metadata_text(&result, 0, 0, "utf8mb4").unwrap().as_deref(),
            Some("mysql")
        );
    }

    #[test]
    fn decoded_text_is_returned_as_is() {
        let result = typed_result(vec![CellState::Decoded(DbValue::Text(
            "utf8_bin".to_string(),
        ))]);
        assert_eq!(
            metadata_text(&result, 0, 0, "utf8mb4").unwrap().as_deref(),
            Some("utf8_bin")
        );
    }

    #[test]
    fn null_stays_none() {
        let result = typed_result(vec![CellState::Decoded(DbValue::Null)]);
        assert_eq!(metadata_text(&result, 0, 0, "utf8mb4").unwrap(), None);
    }

    #[test]
    fn invalid_bytes_fail_instead_of_becoming_hex() {
        let result = typed_result(vec![CellState::Decoded(DbValue::Binary(vec![0xff, 0xfe]))]);
        assert!(matches!(
            metadata_text(&result, 0, 0, "utf8mb4"),
            Err(MetadataReadError::InvalidCharset { .. })
        ));
    }

    #[test]
    fn legacy_fallback_decodes_binary_sidecar() {
        let result = QueryResult {
            sql: "metadata".to_string(),
            columns: vec!["name".to_string()],
            column_meta: vec![QueryColumnMeta::new("name", "VARCHAR")],
            rows: vec![vec![Some("0x6D7973716C".to_string())]],
            binary_cells: vec![BinaryCell {
                row_index: 0,
                column_index: 0,
                bytes: b"mysql".to_vec(),
            }],
            elapsed_ms: 0,
            ..Default::default()
        };
        assert_eq!(
            metadata_text(&result, 0, 0, "utf8mb4").unwrap().as_deref(),
            Some("mysql")
        );
    }
}
